In [ ]:
import numpy as np
x = [(-3,-3),(-1,-1),(1,1),(3,3)]

In [ ]:
x=np.array(x)

In [ ]:
np.matmul(x.T,x)

array([[20, 20],
       [20, 20]])

In [ ]:
x.shape

(4, 2)

In [ ]:
y = np.matmul(x.T,x)
np.cov(y)

array([[0., 0.],
       [0., 0.]])

In [ ]:
import numpy as np
x = [(-3,-3),(-1,-1),(1,1),(3,3)]
x=np.array(x)
y = np.matmul(x.T,x)
evalue, evec = np.linalg.eig(y)
evalue

array([4.00000000e+01, 3.55271368e-15])

In [3]:
import nltk
nltk.download('punkt')

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.


True

In [4]:
from nltk.tokenize import word_tokenize

text = 'Hey dude, I am learning NLP. How super cool is that!'

print (text.split())

print (word_tokenize (text))

['Hey', 'dude,', 'I', 'am', 'learning', 'NLP.', 'How', 'super', 'cool', 'is', 'that!']
['Hey', 'dude', ',', 'I', 'am', 'learning', 'NLP', '.', 'How', 'super', 'cool', 'is', 'that', '!']


In [5]:
import re
text = "How' re you goin'? I hope you're doing great!"
text = re.sub(u"[a-zA-Z0-9]", "", text)
print(text.split())

["'", "'?", "'", '!']
